# Generated by Django 4.2.6 on 2023-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='runregistration',
            name='run',
        ),
        migrations.RemoveField(
            model_name='runregistration',
            name='runner',
        ),
        migrations.RemoveField(
            model_name='runner',
            name='runs',
        ),
        migrations.AddField(
            model_name='runner',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='chosen_run',
            field=models.CharField(blank=True, choices=[('5K', '5K'), ('10K', '10K'), ('Kids', 'Kids')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='healthy_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Run',
        ),
        migrations.DeleteModel(
            name='RunRegistration',
        ),
    ]
